name: Build and deploy package

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Release 

    - name: Download nuget.exe
      run: |
        curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
        chmod +x ./nuget.exe
      shell: bash
      
    - name: Publish to NuGet
      run: |
        ./nuget.exe push ./path/to/nupkg/*.nupkg -ApiKey ${{ secrets.NUGET_TOKEN }} -Source https://api.nuget.org/v3/index.json
      shell: bash
