name: Build and deploy package

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Release --output ./bin/Release

    - name: Publish Package to NuGet
      env:
        nuget-api-key: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push ./bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k $nuget-api-key
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
